# Generated by Django 5.2.5 on 2026-04-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
