# Generated by Django 6.0.3 on 2026-03-21 08:40 (manually reordered for correctness)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connection_category_connection_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Remove old unique constraint that used user1/user2 (clear old)
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
        # Step 2: Add new fields FIRST before any constraint references them
        migrations.AddField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sent_connections',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='received_connections',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='connection',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Step 3: Update status field choices
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('accepted', 'Accepted'),
                    ('declined', 'Declined'),
                    ('blocked', 'Blocked'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        # Step 4: Now that sender + receiver exist, apply the new unique_together
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('sender', 'receiver')},
        ),
        # Step 5: Add indexes on new fields
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['sender', 'status'], name='connections_sender__2b1807_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['receiver', 'status'], name='connections_receive_ae718e_idx'),
        ),
        # Step 6: Remove old fields last
        migrations.RemoveField(
            model_name='connection',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='user2',
        ),
    ]
