# Generated by Django 6.0.3 on 2026-03-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_location_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_roles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='relocation_willingness',
            field=models.BooleanField(default=False),
        ),
    ]
