# Generated by Django 6.0.3 on 2026-03-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_expected_salary_profile_preferred_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_roles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relocation_willingness',
        ),
    ]
