# Generated by Django 6.0.3 on 2026-04-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_expected_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_strength',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_weakness',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
