# Generated by Django 6.0.3 on 2026-03-19 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('online_meeting', 'Online Meeting'), ('onsite_meeting', 'On-site Meeting'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='application_resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('accepted_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
