# Generated by Django 6.0.3 on 2026-03-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_feedback_for_seeker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payroll_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
