# Generated by Django 6.0.3 on 2026-03-21 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_expected_salary_and_more'),
        ('jobs', '0004_rename_view_count_job_views_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='application_job_id_7836e3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['seeker', 'status'], name='application_seeker__c9b2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c6d08d_idx'),
        ),
    ]
