# Generated by Django 6.0.3 on 2026-03-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_application_job_id_7836e3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_snapshot',
            field=models.URLField(blank=True, help_text='Snapshot of the resume at the time of application', null=True),
        ),
    ]
