# Generated by Django 6.0.3 on 2026-03-21 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_resume_snapshot'),
        ('jobs', '0007_alter_job_options_remove_job_experience_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'seeker')},
        ),
        migrations.AddField(
            model_name='application',
            name='payment_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='interview_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('online_meeting', 'Online Meeting'), ('onsite_meeting', 'On-site Meeting'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20),
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume_snapshot',
        ),
    ]
