# Generated by Django 6.0.3 on 2026-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payrollrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
