# Generated by Django 6.0.3 on 2026-03-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_application_deadline_job_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('payroll', 'Monthly Payroll')], default='fixed', max_length=20),
        ),
    ]
