# Generated by Django 6.0.3 on 2026-03-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
