# Generated by Django 6.0.3 on 2026-03-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_jobs_job_recruit_2dee37_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, help_text='e.g. 3-5 years', max_length=100),
        ),
    ]
