# Generated by Django 6.0.3 on 2026-04-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
