# Generated by Django 6.0.3 on 2026-04-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_collaborators_project_repository_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
