# Generated by Django 6.0.3 on 2026-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureditem',
            name='featured_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='featureditem',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
