# Generated by Django 6.0.3 on 2026-04-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0003_alter_featureditem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
