# Generated by Django 6.0.3 on 2026-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_type',
            field=models.CharField(choices=[('user', 'User'), ('company', 'Company'), ('hashtag', 'Hashtag')], default='user', max_length=20),
        ),
    ]
