# Generated by Django 6.0.3 on 2026-03-21 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_follow_follow_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follow_type',
            field=models.CharField(choices=[('user', 'User'), ('company', 'Company')], default='user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='follows_fol_followe_1fd088_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='follows_fol_followi_68fd73_idx'),
        ),
    ]
