# Generated by Django 6.0.3 on 2026-04-06 05:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='Stori',
        ),
        migrations.RenameModel(
            old_name='StoryComment',
            new_name='StoriComment',
        ),
        migrations.RenameModel(
            old_name='StoryLike',
            new_name='StoriLike',
        ),
        migrations.RenameModel(
            old_name='StoryTag',
            new_name='StoriTag',
        ),
        migrations.RenameModel(
            old_name='StoryView',
            new_name='StoriView',
        ),
        migrations.RenameIndex(
            model_name='storilike',
            new_name='stories_sto_story_i_a3f1e1_idx',
            old_name='stories_sto_story_i_8b2cfa_idx',
        ),
        migrations.RenameIndex(
            model_name='storitag',
            new_name='stories_sto_story_i_3dd601_idx',
            old_name='stories_sto_story_i_91f454_idx',
        ),
        migrations.RenameIndex(
            model_name='storiview',
            new_name='stories_sto_story_i_5e665b_idx',
            old_name='stories_sto_story_i_b8f927_idx',
        ),
    ]
