# Generated by Django 6.0.3 on 2026-04-06 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_rename_story_stori_rename_storycomment_storicomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stori',
            name='images',
        ),
        migrations.CreateModel(
            name='StoriMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='story_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='stories.stori')),
            ],
            options={
                'indexes': [models.Index(fields=['story'], name='stories_sto_story_i_b1bb7c_idx')],
                'unique_together': {('story', 'author')},
            },
        ),
    ]
