# Generated by Django 6.0.3 on 2026-03-21 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_options_and_more'),
        ('meetings', '0002_meeting_agenda_meeting_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AddField(
            model_name='meeting',
            name='candidate_no_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('online', 'Online Meeting'), ('onsite', 'On-site Meeting'), ('phone', 'Phone Call')], max_length=10),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['application', 'status'], name='meetings_me_applica_7f1e73_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['scheduled_at'], name='meetings_me_schedul_bf3e55_idx'),
        ),
    ]
