# Generated by Django 6.0.3 on 2026-04-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_meeting_options_meeting_candidate_no_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_documents',
            field=models.FileField(blank=True, null=True, upload_to='meeting_documents/'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
