"""
Django settings for jobrynbackend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

import os

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-r$c(x(yh^ga))!$%71$c&6*%q!!#rp0j=k7^t$bfvs%ex5!n+^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # Unfold (must be before django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third Party
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'django_filters',
    'channels',
    'phonenumber_field',
    'corsheaders',
    
    # Custom Apps
    'account',
    'profiles',
    'experiences',
    'educations',
    'skills',
    'certifications',
    'projects',
    'featured',
    'companies',
    'jobs',
    'applications',
    'connections',
    'follows',
    'posts',
    'newsletters',
    'messages',
    'notifications',
    'learning',
    'billing',
    'meetings',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobrynbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobrynbackend.wsgi.application'
ASGI_APPLICATION = 'jobrynbackend.asgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jobryn',
        'USER': 'biznexcloud.com@gmail.com',
        'PASSWORD': 'Ramesh@5611',
        'HOST': '204.10.163.10',
        'PORT': '3307',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kathmandu'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


AUTH_USER_MODEL = 'account.User'

# Email backend settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'          # or your SMTP provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'rsah3798@gmail.com'
EMAIL_HOST_PASSWORD = 'junxepvlojhhgudd'  # use App Password for Gmail
DEFAULT_FROM_EMAIL = 'rsah3798@gmail.com'

# DRF Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Jobryn API',
    'DESCRIPTION': 'Professional Job Portal and Social Network API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}

# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Khalti
KHALTI_SECRET_KEY = 'test_secret_key_placeholder' # REPLACE IN PRODUCTION

# CORS
CORS_ALLOW_ALL_ORIGINS = True
UNFOLD = {
    "SITE_TITLE": "Jobryn Admin",
    "SITE_HEADER": "Jobryn Management Portal",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: static("img/logo.png"),
    "SITE_FAVICON": lambda request: static("img/logo.png"),
    "SITE_SYMBOL": "work",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": True,
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "DASHBOARD_CALLBACK": "jobrynbackend.dashboard.dashboard_callback",
    "DASHBOARD": {
        "widgets": [
            {
                "title": _("Key Performance Indicators"),
                "width": "full",
                "type": "stats",
                "stats": "kpi_stats",
            },
            {
                "title": _("Hiring Pipeline (Last 6 Months)"),
                "width": "half",
                "height": 300,
                "type": "chart",
                "chart": {
                    "type": "line",
                    "data": "hiring_chart",
                },
            },
            {
                "title": _("Revenue Performance (NPR)"),
                "width": "half",
                "height": 300,
                "type": "chart",
                "chart": {
                    "type": "bar",
                    "data": "revenue_chart",
                },
            },
            {
                "title": _("Social Engagement"),
                "width": "half",
                "height": 300,
                "type": "chart",
                "chart": {
                    "type": "doughnut",
                    "data": "engagement_chart",
                },
            },
            {
                "title": _("Top Talent Skills"),
                "width": "half",
                "height": 300,
                "type": "chart",
                "chart": {
                    "type": "radar",
                    "data": "talent_chart",
                },
            },
        ],
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("🔐 Authentication & Roles"),
                "separator": False,
                "items": [
                    {"title": _("Dashboard"), "link": reverse_lazy("admin:index"), "icon": "dashboard"},
                    {"title": _("Groups & Roles"), "link": reverse_lazy("admin:auth_group_changelist"), "icon": "lock_person"},
                    {"title": _("Users"), "link": reverse_lazy("admin:account_user_changelist"), "icon": "people"},
                    {"title": _("User Profiles"), "link": reverse_lazy("admin:profiles_profile_changelist"), "icon": "account_circle"},
                ],
            },
            {
                "title": "💼 Recruitment & Jobs",
                "separator": True,
                "items": [
                    {"title": "Companies", "link": reverse_lazy("admin:companies_company_changelist"), "icon": "business"},
                    {"title": "Job Postings", "link": reverse_lazy("admin:jobs_job_changelist"), "icon": "work"},
                    {"title": "Applications", "link": reverse_lazy("admin:applications_application_changelist"), "icon": "person_search"},
                    {"title": "Meetings", "link": reverse_lazy("admin:meetings_meeting_changelist"), "icon": "event"},
                ],
            },
            {
                "title": "🎓 Portfolio",
                "separator": True,
                "items": [
                    {"title": "Experiences", "link": reverse_lazy("admin:experiences_experience_changelist"), "icon": "history_edu"},
                    {"title": "Educations", "link": reverse_lazy("admin:educations_education_changelist"), "icon": "school"},
                    {"title": "Skills", "link": reverse_lazy("admin:skills_skill_changelist"), "icon": "psychology"},
                    {"title": "Certifications", "link": reverse_lazy("admin:certifications_certification_changelist"), "icon": "verified"},
                    {"title": "Projects", "link": reverse_lazy("admin:projects_project_changelist"), "icon": "folder_shared"},
                ],
            },
            {
                "title": "🌐 Social",
                "separator": True,
                "items": [
                    {"title": "Feed Posts", "link": reverse_lazy("admin:posts_post_changelist"), "icon": "rss_feed"},
                    {"title": "Connections", "link": reverse_lazy("admin:connections_connection_changelist"), "icon": "handshake"},
                    {"title": "Follows", "link": reverse_lazy("admin:follows_follow_changelist"), "icon": "group_add"},
                    {"title": "Messages", "link": reverse_lazy("admin:chat_messages_message_changelist"), "icon": "chat"},
                    {"title": "Notifications", "link": reverse_lazy("admin:notifications_notification_changelist"), "icon": "notifications"},
                ],
            },
            {
                "title": "📚 Learning",
                "separator": True,
                "items": [
                    {"title": "Courses", "link": reverse_lazy("admin:learning_course_changelist"), "icon": "menu_book"},
                    {"title": "Enrollments", "link": reverse_lazy("admin:learning_enrollment_changelist"), "icon": "local_library"},
                ],
            },
            {
                "title": "💰 Financials",
                "separator": True,
                "items": [
                    {"title": "Invoices", "link": reverse_lazy("admin:billing_invoice_changelist"), "icon": "receipt_long"},
                    {"title": "Payments", "link": reverse_lazy("admin:billing_payment_changelist"), "icon": "account_balance_wallet"},
                    {"title": "Payroll Records", "link": reverse_lazy("admin:billing_payrollrecord_changelist"), "icon": "payments"},
                ],
            },
            {
                "title": "📧 Communication",
                "separator": True,
                "items": [
                    {"title": "Newsletters", "link": reverse_lazy("admin:newsletters_newsletter_changelist"), "icon": "mail"},
                    {"title": "Subscribers", "link": reverse_lazy("admin:newsletters_subscriber_changelist"), "icon": "subscriptions"},
                ],
            },
        ],
    },
}


# 📝 LOGGING
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
