# Generated by Django 6.0.3 on 2026-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_size_company_founded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='founded_at',
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '201-500 employees'), ('501-1000', '501-1,000 employees'), ('1001-5000', '1,001-5,000 employees'), ('5001-10000', '5,001-10,000 employees'), ('10001+', '10,001+ employees')], max_length=20),
        ),
    ]
