# Generated by Django 6.0.3 on 2026-03-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_founded_at_company_founded_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
