# Generated by Django 6.0.3 on 2026-03-21 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_facebook_url_company_twitter_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_covers/'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1,000 employees'), ('1001-5000', '1,001-5,000 employees'), ('5001+', '5,001+ employees')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner', 'is_verified'], name='companies_c_owner_i_34f22a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='companies_c_created_301a54_idx'),
        ),
    ]
