# Generated by Django 6.0.3 on 2026-04-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_options_remove_company_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
