# Generated by Django 6.0.3 on 2026-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
