# Generated by Django 6.0.3 on 2026-04-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_certification_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certification',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
