# Generated by Django 6.0.3 on 2026-04-12 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0008_alter_company_id'),
        ('educations', '0005_alter_education_id'),
        ('experiences', '0005_alter_experience_id'),
        ('jobs', '0010_job_images'),
        ('projects', '0006_alter_project_id'),
        ('skills', '0005_alter_endorsement_id_alter_skill_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_company', to='companies.company')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_education', to='educations.education')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_experience', to='experiences.experience')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_jobs', to='jobs.job')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_projects', to='projects.project')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_skills', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
