# Generated by Django 6.0.3 on 2026-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert'), ('master', 'Master')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='userskill',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
