# Generated by Django 6.0.3 on 2026-03-21 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_userskill_proficiency_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('design', 'Design'), ('management', 'Management'), ('communication', 'Communication'), ('data', 'Data & Analytics'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('language', 'Language'), ('other', 'Other')], default='technical', max_length=30),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userskill',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='skills_skil_categor_853dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user', 'proficiency_level'], name='skills_user_user_id_56a955_idx'),
        ),
    ]
