# Generated by Django 6.0.3 on 2026-04-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0002_education_activities_societies_education_gpa_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='education_certificates/'),
        ),
        migrations.AddField(
            model_name='education',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
